package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// --- Light Theme Palette (Professional Polish) ---
val LightPrimary = Color(0xFF0061A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F7)
val LightOnSecondaryContainer = Color(0xFF101C2B)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF2DAFF)
val LightOnTertiaryContainer = Color(0xFF251431)
val LightBackground = Color(0xFFF7F9FF)
val LightOnBackground = Color(0xFF191C1E)
val LightSurface = Color(0xFFF7F9FF)
val LightOnSurface = Color(0xFF191C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)

// --- Dark Theme Palette ---
val DarkPrimary = Color(0xFFA1C9FF)
val DarkOnPrimary = Color(0xFF00325A)
val DarkPrimaryContainer = Color(0xFF00497E)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF253140)
val DarkSecondaryContainer = Color(0xFF3B4858)
val DarkOnSecondaryContainer = Color(0xFFD7E3F7)
val DarkBackground = Color(0xFF111416)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF111416)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7D0)
val DarkOutline = Color(0xFF8D9199)
